/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "asociaciones.h"


void
asociacion_1(char *host){
	CLIENT *clnt;
	Existe  *result_1;
	Leer  *result_2;
	Existe  *result_3;
	Resultado  *result_4;
	int argumentoID;
	char clave[250];
    char valor[250];    
	int enumerar_1_arg1;

#ifndef	DEBUG
	clnt = clnt_create (host, ASOCIACION, ASOCIACION_VER, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */
 int opcion=0;
    while(opcion!=-1){
        printf("1 - Poner Asociacion\n");
        printf("2 - Obtener Asociacion\n");
        printf("3 - Borrar Asociacion\n");
        printf("4 - Enumerar\n");
        printf("-1 - Salir\n");
		printf("OPCION: ");	scanf("%d",&opcion);
	switch(opcion){
        	case 1:
			    printf("ID: "); 	scanf("%d",&argumentoID);
			    printf("Clave: ");	scanf("%s",clave);
			    printf("Valor: ");	scanf("%s",valor);
			    printf("ASOCIACION NUEVA: ID: %d CLAVE: %s VALOR: %s.\n",argumentoID,clave,valor);
			 
				result_1 = ponerasociacion_1(argumentoID, clave, valor, clnt);
				if (result_1 == (Existe *) NULL) {
					clnt_perror (clnt, "call failed");
				}
				else{
					if (*result_1 == Fal)
			   			printf("DATO NUEVO INSERTADO\n");
			  		if (*result_1 == Ver)
			   			printf("DATO MODIFICADO:\n");

				}
			break;

			case 2:
			  	printf("ID: ");   	scanf("%d",&argumentoID);
			    printf("Clave: ");	scanf("%s",clave);
			    printf("ASOCIACION A CONSULTAR: ID: %d CLAVE: %s\n",argumentoID,clave);
				
				result_2 = obtenerasociacion_1(argumentoID, clave, clnt);
			   	printf("SALE DE LA LLAMADA:\n");
				if (result_2 == (Leer *) NULL) {
					clnt_perror (clnt, "call failed");
				}
				else{
			  		if (result_2->errno == Ver)
			   			printf("Valor obtenido: %s\n",*result_2->Leer_u.v);
					else
			   			printf("NO HAY DATOS PARA MOSTRAR.Par ID/CLAVE no existe\n");

				}
			break;

			case 3:
			 	printf("ID: ");		scanf("%d",&argumentoID);
			    printf("Clave: ");	scanf("%s",clave);
			    printf("ASOCIACION A BORRAR: ID: %d CLAVE: %s .\n",argumentoID,clave);
				result_3 = borrarasociacion_1(argumentoID, clave, clnt);
				if (result_3 == (Existe *) NULL) {
					clnt_perror (clnt, "call failed");	}
				else{
					if (*result_3 == Fal)
			   			printf("NO SE HA ENCONTRADO DATO A ELIMINAR\n");
			  		if (*result_3 == Ver)
			   			printf("DATO ELIMINADO CON EXITO:\n");

				}
			break;

			case 4:
			 	printf("ID: ");		scanf("%d",&argumentoID);
			    printf("ID a mostrar: %d \n",argumentoID);
				result_4 = enumerar_1(argumentoID, clnt);
				if (result_4 == (Resultado *) NULL) {
					clnt_perror (clnt, "call failed");
				}
				else{
					if (result_4->errno == Fal)
			   			printf("NO HAY DATOS PARA MOSTRAR.P ar ID/CLAVE no existe\n");
			  		if (result_4->errno == Ver)
			   			printf("Asociacion Obtenida: %s\n",result_4->Resultado_u.resultado->c);
				}
			break;
			case -1:
			 	printf("SALIENDO \n");
			break;

			default:
			    printf("Opcion Incorrecta .\n");
			break;

	}			
	}				
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	asociacion_1 (host);
exit (0);
}
