/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "asociaciones.h"

bool_t
xdr_clave (XDR *xdrs, clave *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, objp, TAMSTRING))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_valor (XDR *xdrs, valor *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, objp, TAMSTRING))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_Existe (XDR *xdrs, Existe *objp)
{
	register int32_t *buf;

	 if (!xdr_enum (xdrs, (enum_t *) objp))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_Asociacion (XDR *xdrs, Asociacion *objp)
{
	register int32_t *buf;

	 if (!xdr_clave (xdrs, &objp->c))
		 return FALSE;
	 if (!xdr_valor (xdrs, &objp->v))
		 return FALSE;
	 if (!xdr_pointer (xdrs, (char **)&objp->siguienteAsociacion, sizeof (Asociacion), (xdrproc_t) xdr_Asociacion))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_Conjunto (XDR *xdrs, Conjunto *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->ID))
		 return FALSE;
	 if (!xdr_pointer (xdrs, (char **)&objp->a, sizeof (Asociacion), (xdrproc_t) xdr_Asociacion))
		 return FALSE;
	 if (!xdr_pointer (xdrs, (char **)&objp->siguienteConjunto, sizeof (Conjunto), (xdrproc_t) xdr_Conjunto))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_Leer (XDR *xdrs, Leer *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->errno))
		 return FALSE;
	switch (objp->errno) {
	case 0:
		 if (!xdr_pointer (xdrs, (char **)&objp->Leer_u.v, sizeof (valor), (xdrproc_t) xdr_valor))
			 return FALSE;
		break;
	default:
		break;
	}
	return TRUE;
}

bool_t
xdr_Resultado (XDR *xdrs, Resultado *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->errno))
		 return FALSE;
	switch (objp->errno) {
	case 0:
		 if (!xdr_pointer (xdrs, (char **)&objp->Resultado_u.resultado, sizeof (Asociacion), (xdrproc_t) xdr_Asociacion))
			 return FALSE;
		break;
	default:
		break;
	}
	return TRUE;
}

bool_t
xdr_ponerasociacion_1_argument (XDR *xdrs, ponerasociacion_1_argument *objp)
{
	 if (!xdr_int (xdrs, &objp->arg1))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->arg2, ~0))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->arg3, ~0))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_obtenerasociacion_1_argument (XDR *xdrs, obtenerasociacion_1_argument *objp)
{
	 if (!xdr_int (xdrs, &objp->arg1))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->arg2, ~0))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_borrarasociacion_1_argument (XDR *xdrs, borrarasociacion_1_argument *objp)
{
	 if (!xdr_int (xdrs, &objp->arg1))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->arg2, ~0))
		 return FALSE;
	return TRUE;
}
