/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _ARITMETICA_H_RPCGEN
#define _ARITMETICA_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct sum_1_argument {
	int arg1;
	int arg2;
};
typedef struct sum_1_argument sum_1_argument;

struct mul_1_argument {
	int arg1;
	int arg2;
};
typedef struct mul_1_argument mul_1_argument;

struct res_1_argument {
	int arg1;
	int arg2;
};
typedef struct res_1_argument res_1_argument;

struct div_1_argument {
	int arg1;
	int arg2;
};
typedef struct div_1_argument div_1_argument;

#define PRACTICA1 0x20000001
#define VERSIONACTOCA1 1

#if defined(__STDC__) || defined(__cplusplus)
#define sum 1
extern  int * sum_1(int , int , CLIENT *);
extern  int * sum_1_svc(int , int , struct svc_req *);
#define mul 2
extern  int * mul_1(int , int , CLIENT *);
extern  int * mul_1_svc(int , int , struct svc_req *);
#define res 3
extern  int * res_1(int , int , CLIENT *);
extern  int * res_1_svc(int , int , struct svc_req *);
#define div 4
extern  int * div_1(int , int , CLIENT *);
extern  int * div_1_svc(int , int , struct svc_req *);
extern int practica1_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define sum 1
extern  int * sum_1();
extern  int * sum_1_svc();
#define mul 2
extern  int * mul_1();
extern  int * mul_1_svc();
#define res 3
extern  int * res_1();
extern  int * res_1_svc();
#define div 4
extern  int * div_1();
extern  int * div_1_svc();
extern int practica1_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_sum_1_argument (XDR *, sum_1_argument*);
extern  bool_t xdr_mul_1_argument (XDR *, mul_1_argument*);
extern  bool_t xdr_res_1_argument (XDR *, res_1_argument*);
extern  bool_t xdr_div_1_argument (XDR *, div_1_argument*);

#else /* K&R C */
extern bool_t xdr_sum_1_argument ();
extern bool_t xdr_mul_1_argument ();
extern bool_t xdr_res_1_argument ();
extern bool_t xdr_div_1_argument ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_ARITMETICA_H_RPCGEN */
