package trabajotema2;
import java.io.FileInputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.lang.reflect.InvocationTargetException;
import java.lang.reflect.Method;
import java.net.URL;
import java.net.URLClassLoader;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;

public class VentanaTrabajo extends javax.swing.JFrame {
    ClassLoader classLoader = VentanaTrabajo.class.getClassLoader();
    FileInputStream fis;
    Class aClass, bClass;
    Method[] methods,methods2;
    Object object,oo;
    URLClassLoader urlClassLoader;
    
    public VentanaTrabajo() {
        initComponents();
        botonAbrirB.setVisible(false);
        panelInferior.setVisible(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelInfo = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        areaTexto = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        botonAbrir = new javax.swing.JButton();
        botonAbrirB = new javax.swing.JButton();
        panelInferior = new javax.swing.JPanel();
        panelLocal = new javax.swing.JPanel();
        jButton9 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        botonDirecionClase = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        panelRemotop = new javax.swing.JPanel();
        jButton8 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        campoTexto = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridLayout(1, 0));

        panelInfo.setLayout(new java.awt.BorderLayout());

        areaTexto.setColumns(20);
        areaTexto.setRows(5);
        areaTexto.setText("1.- Paso 1, cargar \".class\"\n2.- Abrir ByteCode\n3.- Llamar a los metodos");
        jScrollPane1.setViewportView(areaTexto);

        panelInfo.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.LINE_AXIS));

        botonAbrir.setText("Abrir \".class\"");
        botonAbrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAbrirActionPerformed(evt);
            }
        });
        jPanel1.add(botonAbrir);

        botonAbrirB.setText("Abrir \"bytecode\"");
        botonAbrirB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAbrirBActionPerformed(evt);
            }
        });
        jPanel1.add(botonAbrirB);

        panelInfo.add(jPanel1, java.awt.BorderLayout.PAGE_START);

        panelInferior.setLayout(new javax.swing.BoxLayout(panelInferior, javax.swing.BoxLayout.LINE_AXIS));

        panelLocal.setBorder(javax.swing.BorderFactory.createTitledBorder("Llamar a metodos de Bytecode"));
        panelLocal.setLayout(new javax.swing.BoxLayout(panelLocal, javax.swing.BoxLayout.LINE_AXIS));

        jButton9.setText("Mostrar Metodos");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        panelLocal.add(jButton9);

        jButton1.setText("obtenerNombreClase ");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        panelLocal.add(jButton1);

        botonDirecionClase.setText("obtenerDirecciónClase");
        botonDirecionClase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonDirecionClaseActionPerformed(evt);
            }
        });
        panelLocal.add(botonDirecionClase);

        jButton2.setText("obtenerRutaCompleta ");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        panelLocal.add(jButton2);

        jButton4.setText("getClass");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        panelLocal.add(jButton4);

        panelInferior.add(panelLocal);

        panelRemotop.setBorder(javax.swing.BorderFactory.createTitledBorder("Llamar a metodos de \"clase a descubir\""));
        panelRemotop.setLayout(new javax.swing.BoxLayout(panelRemotop, javax.swing.BoxLayout.LINE_AXIS));

        jButton8.setText("Mostrar Metodos");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        panelRemotop.add(jButton8);

        jButton5.setText("computa(DNI: 45712353)");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        panelRemotop.add(jButton5);

        jButton3.setText("Computa Texto:");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        panelRemotop.add(jButton3);

        campoTexto.setText("00000000");
        campoTexto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoTextoActionPerformed(evt);
            }
        });
        panelRemotop.add(campoTexto);

        panelInferior.add(panelRemotop);

        panelInfo.add(panelInferior, java.awt.BorderLayout.PAGE_END);

        getContentPane().add(panelInfo);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonAbrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAbrirActionPerformed
        try {      
            aClass = classLoader.loadClass("ClaseASerializar");
            botonAbrir.setVisible(false);
            botonAbrirB.setVisible(true);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(VentanaTrabajo.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_botonAbrirActionPerformed

    private void botonAbrirBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAbrirBActionPerformed
    JFileChooser dlg = new JFileChooser();
    int resp = dlg.showOpenDialog(this);  
        if(resp==JFileChooser.APPROVE_OPTION){
            try{
                fis = new FileInputStream(dlg.getSelectedFile().toString());
                botonAbrirB.setVisible(false);
            }catch(Exception ex){
                System.err.println("ERROR AL LEER ARCHIVO");
            }
        }
        this.cargarArchivos();
        panelInferior.setVisible(true);                                      
    }//GEN-LAST:event_botonAbrirBActionPerformed

    private void botonDirecionClaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonDirecionClaseActionPerformed
        String nombre = "obtenerDirecciónClase";
        try {
            Method  method = aClass.getMethod(nombre,null);            
            Object o = method.invoke(object, null);
            String salida=o.toString(); 
            areaTexto.setText("Direcion de la clase: "+salida);
        } catch (NoSuchMethodException ex) {
            Logger.getLogger(VentanaTrabajo.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SecurityException ex) {
            Logger.getLogger(VentanaTrabajo.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            Logger.getLogger(VentanaTrabajo.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IllegalArgumentException ex) {
            Logger.getLogger(VentanaTrabajo.class.getName()).log(Level.SEVERE, null, ex);
        } catch (InvocationTargetException ex) {
            Logger.getLogger(VentanaTrabajo.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_botonDirecionClaseActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String nombre = "obtenerNombreClase";
        try {
            Method  method = aClass.getMethod(nombre,null);            
            Object o = method.invoke(object, null);
            String salida=o.toString(); 
            areaTexto.setText("Direcion de la clase: "+salida);
        } catch (NoSuchMethodException ex) {
            Logger.getLogger(VentanaTrabajo.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SecurityException ex) {
            Logger.getLogger(VentanaTrabajo.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            Logger.getLogger(VentanaTrabajo.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IllegalArgumentException ex) {
            Logger.getLogger(VentanaTrabajo.class.getName()).log(Level.SEVERE, null, ex);
        } catch (InvocationTargetException ex) {
            Logger.getLogger(VentanaTrabajo.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String nombre = "obtenerRutaCompleta";
        try {
            Method  method = aClass.getMethod(nombre,null);            
            Object o = method.invoke(object, null);
            String salida=o.toString(); 
            areaTexto.setText("Direcion de la clase: "+salida);
        } catch (NoSuchMethodException ex) {
            Logger.getLogger(VentanaTrabajo.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SecurityException ex) {
            Logger.getLogger(VentanaTrabajo.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            Logger.getLogger(VentanaTrabajo.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IllegalArgumentException ex) {
            Logger.getLogger(VentanaTrabajo.class.getName()).log(Level.SEVERE, null, ex);
        } catch (InvocationTargetException ex) {
            Logger.getLogger(VentanaTrabajo.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        String nombre = "getClass";
        try {
            Method  method = aClass.getMethod(nombre,null);            
            Object o = method.invoke(object, null);
            String salida=o.toString(); 
            areaTexto.setText("Direcion de la clase: "+salida);
        } catch (NoSuchMethodException ex) {
            Logger.getLogger(VentanaTrabajo.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SecurityException ex) {
            Logger.getLogger(VentanaTrabajo.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            Logger.getLogger(VentanaTrabajo.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IllegalArgumentException ex) {
            Logger.getLogger(VentanaTrabajo.class.getName()).log(Level.SEVERE, null, ex);
        } catch (InvocationTargetException ex) {
            Logger.getLogger(VentanaTrabajo.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        Method method1;
        Object o2=null;
        try {
            method1 = bClass.getMethod("computa",String.class);
            o2 = method1.invoke(oo, "45712353");
        } catch (NoSuchMethodException ex) {
            Logger.getLogger(VentanaTrabajo.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SecurityException ex) {
            Logger.getLogger(VentanaTrabajo.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            Logger.getLogger(VentanaTrabajo.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IllegalArgumentException ex) {
            Logger.getLogger(VentanaTrabajo.class.getName()).log(Level.SEVERE, null, ex);
        } catch (InvocationTargetException ex) {
            System.out.println("El DNI no es valido, formato xxxxxxxx SIN LETRA");
           // Logger.getLogger(VentanaTrabajo.class.getName()).log(Level.SEVERE, null, ex);
        }

        if(o2!=null)
                areaTexto.setText("Salida de la llamada a funcion Computa: "+o2);

    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        methods = aClass.getMethods();
        //Los mostramos por pantalla
        areaTexto.setText(" ");
        for (Method item : methods) {
            areaTexto.setText(areaTexto.getText()+"Metodo con nombre: "+item.getName()+" y numero de parametros:"+item.getParameterCount()+"\n");
        }
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        methods2 = bClass.getMethods();
        //Los mostramos por pantalla
        areaTexto.setText(" ");
        for (Method item : methods2) {
            areaTexto.setText(areaTexto.getText()+"Metodo con nombre: "+item.getName()+" y numero de parametros:"+item.getParameterCount()+"\n");
        }
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        Method method1;
        String entrada=new String(campoTexto.getText().toString());
        Object o2=null;
        try {
            method1 = bClass.getMethod("computa",String.class);
           o2 = method1.invoke(oo, entrada);
        } catch (NoSuchMethodException ex) {
            Logger.getLogger(VentanaTrabajo.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SecurityException ex) {
            Logger.getLogger(VentanaTrabajo.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            Logger.getLogger(VentanaTrabajo.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IllegalArgumentException ex) {
            Logger.getLogger(VentanaTrabajo.class.getName()).log(Level.SEVERE, null, ex);
        } catch (InvocationTargetException ex) {
          //  Logger.getLogger(VentanaTrabajo.class.getName()).log(Level.SEVERE, null, ex);
            System.out.println("El DNI no es valido, formato xxxxxxxx SIN LETRA");
        }
        if(o2!=null)
            areaTexto.setText("Salida de la llamada a funcion Computa: "+o2);

        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void campoTextoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoTextoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoTextoActionPerformed

    
public void cargarArchivos(){
         ObjectInputStream ois;

try {
            ois = new ObjectInputStream(fis);

        object = (Object) ois.readObject();
                
        String nombre = "obtenerDirecciónClase";
        System.out.println(nombre);
            Method method = aClass.getMethod(nombre,null);
            Object o = method.invoke(object, null);
            String direccion=o.toString();
            //String direccion=o.toString().split(".class")[0];
            System.out.println(direccion);
             nombre = "obtenerNombreClase";
            System.out.println(nombre);
             method = aClass.getMethod(nombre,null);
             o = method.invoke(object, null);
            String nombreClase=o.toString();
            System.out.println(nombreClase);        
            ois.close();
            
        urlClassLoader = new URLClassLoader(new URL[]{new URL(direccion)});

        bClass = urlClassLoader.loadClass(nombreClase);
        methods2 = bClass.getMethods();
        oo = bClass.newInstance();

} catch (IOException ex) {
    Logger.getLogger(VentanaTrabajo.class.getName()).log(Level.SEVERE, null, ex);
}       catch (ClassNotFoundException ex) {
            Logger.getLogger(VentanaTrabajo.class.getName()).log(Level.SEVERE, null, ex);
        } catch (NoSuchMethodException ex) {
            Logger.getLogger(VentanaTrabajo.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SecurityException ex) {
            Logger.getLogger(VentanaTrabajo.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            Logger.getLogger(VentanaTrabajo.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IllegalArgumentException ex) {
            Logger.getLogger(VentanaTrabajo.class.getName()).log(Level.SEVERE, null, ex);
        } catch (InvocationTargetException ex) {
            Logger.getLogger(VentanaTrabajo.class.getName()).log(Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            Logger.getLogger(VentanaTrabajo.class.getName()).log(Level.SEVERE, null, ex);
        }
        
}
    /**
     * @param args the command line arguments
     */
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaTrabajo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaTrabajo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaTrabajo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaTrabajo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaTrabajo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea areaTexto;
    private javax.swing.JButton botonAbrir;
    private javax.swing.JButton botonAbrirB;
    private javax.swing.JButton botonDirecionClase;
    private javax.swing.JTextField campoTexto;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel panelInferior;
    private javax.swing.JPanel panelInfo;
    private javax.swing.JPanel panelLocal;
    private javax.swing.JPanel panelRemotop;
    // End of variables declaration//GEN-END:variables
}
